### ISSUE TITLE
Enable more animation functions

### ISSUE THREAD

**Issue by jwasilgeo** [sarahbellum/Canvas-Flowmap-Layer#3]
I think we can get rid of our own custom animation functions and instead use [`dojo/fx/easing`](http://dojotoolkit.org/reference-guide/1.10/dojo/fx/easing.html#dojo-fx-easing) which appears to provide a host of functions to choose from.  This could reduce the source code we have to maintain and provide users/devs with far more options.

If this dojo module works the way I think it does from my massive research spanning a whole 10 minutes, then I propose that we change the `animationStyle` property to accept any of the function names in this dojo module, e.g.:

```javascript
new CanvasFlowmapLayer({
  animationStyle: 'quadIn' // string, can be any of the function names in dojo/fx/easing
});
```

In the layer source code I believe we can then alter values as needed by simply passing them into, for example:

```javascript
easing.quadIn(2) // returns 4
easing.quadIn(4) // returns 16
// and so on
```

Thoughts?

**Comment by jwasilgeo** [comment]
Upon further :male_detective: work, I'm not sure that `dojo/fx/easing` is really intended for use on its own to change javascript properties.  The docs push for using it directly with dojo's DOM animation classes.

The benefit of using a dojo module directly meant not needing to use 3rd-party libs to further complicate the layer codebase, but I think it might be necessary to look into using (for example) one of these instead:

- https://github.com/tweenjs/tween.js
- http://jeremyckahn.github.io/shifty
- www.createjs.com/tweenjs

**Comment by jwasilgeo** [comment]
@sarahbellum here's a rough implementation of https://github.com/tweenjs/tween.js and using its bounce out (dramatic, yes, totally) easing option over a 4s duration:
![test](https://cloud.githubusercontent.com/assets/4933392/24074436/b77dd7f2-0bde-11e7-9177-2ab0cf23ac06.gif)

**Comment by sarahbellum** [comment]
@jwasilgeo gif looks great. The efficiency aspect sounds good to me. 😸
