### ISSUE TITLE
Roadmap: JSAPI 4.x support

### ISSUE THREAD

**Issue by jwasilgeo** [sarahbellum/Canvas-Flowmap-Layer#4]
Currently `Canvas-Flowmap-Layer` only works with JSAPI 3.x and extends `esri/layers/GraphicsLayer`. High-level summary:
- It manually inserts its own `<canvas>` elements into very specific places within the map in the DOM.
- It listens to several map events to know precisely when to clear and/or redraw its own `<canvas>` elements.
- It uses point graphics, but applies symbology so that they are "ghost graphics"; this is to enable `click`, `mouse-over`, etc. functionality that developers using the `GraphicsLayer` are already familiar with.

The paradigm for creating custom layers in JSAPI 4.x is clearly different than JSAPI 3.x.  I'm opening this issue as a placeholder for investigating what it'll take to create a custom JSAPI 4.x layer that'll work in both a `MapView` and `SceneView`.

cc @ycabon

**Comment by jwasilgeo** [comment]
Development for this is happening in the branch named [`jsapi-4`](https://github.com/sarahbellum/Canvas-Flowmap-Layer/tree/jsapi-4)

**Comment by jwasilgeo** [comment]
Closed in PR #8

**Comment by nzjs** [comment]
Is there any scope to getting Tween animations working in JSAPI 4.x? 

From my testing and what I can see, they only work with 3.x.

**Comment by jwasilgeo** [comment]
We'd love to get them in there for 4.x sometime, but haven't had a spare moment to look into that yet. I'd like to first get the frame rate performance increased for our 4.x layer. You're right, the animations are only available in JSAPI 3.x or in the [Leaflet layer version](https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer).
