### ISSUE TITLE
Trying to run demo locally 

### ISSUE THREAD

**Issue by betim** [sarahbellum/Canvas-Flowmap-Layer#7]
Hi,

Not a JS dev here. I tried to run the main demo locally, but it fails to load config.js.

From what I can see, esri requires config.js to be publicly available right? If yes, is there a workaround this?

Cheers

**Comment by betim** [comment]
Sorry, this is entirely my fault. I didn't clone the repo and try to run the main demo, but rather copied files one by one.

The problem was: it tried to load config.js from http://config.js/ -- that's why I was assuming that it is required from esri.

This now works, but I still have no idea how config.js is loaded.

Regards

**Comment by jwasilgeo** [comment]
No worries and glad you got it working.  As for config.js, we instruct Dojo (what the Esri JSAPI is built on top of) to become aware of other JavaScript resources in addition to the modules that it comes with out of the box.  In our demos, we inform it that we need to be able to reference some local js files like this:
https://github.com/sarahbellum/Canvas-Flowmap-Layer/blob/master/demos/main/index.html#L28-L41

**Comment by betim** [comment]
This answers all my questions. Thanks
